# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f575b454394b52db15af140d64c12f45690052e959136cfa527768e7d0714f9e0d4e74bdc750c86f29c9bfb3c08a7c4395cabe491c0bf457b9dc1e0220223e3

test:
  secret_key_base: ee420dce15f2a30580151322767f9eb567a3b0d193348fe02e373ae5495acc74dae4bd4efc70e44b5d27e08e49e8b4782aadb63d95790be24ba571b75a7dea17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
